name: Build and Deploy Kubernetes cluster running Milvus
on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
    secrets:
      GOOGLE_CREDENTIALS:
        required: true

jobs:

  terraform-apply-and-helm-install:
    runs-on: ubuntu-latest
    env:
      working-dir: ./src/terraform
      GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        working-directory: ${{ env.working-dir }}
        run: terraform init
                
      - name: Terraform Plan
        working-directory: ${{ env.working-dir }}
        id: plan
        run: |
          terraform workspace select dev
          terraform plan -var-file=tfvars/${{ inputs.env-name }}.tfvars -out=tf.plan
          
#       - name: Terraform Apply
#         working-directory: ${{ env.working-dir }}
#         run: |
#           terraform workspace select dev
#           terraform apply -auto-approve -input=false tf.plan
          
#       - name: Install Gcloud for Milvus
#         run: |
#           echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
#           curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
#           sudo apt-get update && sudo apt-get install google-cloud-cli
    
      - name: Install Helm for Milvus
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      
      - name: Run Milvus
        run: |
          gcloud container clusters get-credentials $(terraform output cluster_name)
          helm repo add milvus https://milvus-io.github.io/milvus-helm/
          helm repo update
          helm install milvus_deploy milvus/milvus -f helm_values.yaml
          
          
