name: Build and Deploy Kubernetes cluster running Milvus
on:
  workflow_call:
    inputs:
      env-name:
        required: true
        type: string
    secrets:
      GOOGLE_CREDENTIALS:
        required: true

jobs:

  terraform-apply-and-helm-install:
    runs-on: ubuntu-latest
    env:
      working-dir: ./src/terraform
      GOOGLE_BACKEND_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform Init
        working-directory: ${{ env.working-dir }}
        run: terraform init
        
      - name: Terraform Plan
        working-directory: ${{ env.working-dir }}
        id: plan
        run: terraform plan -no-color -input=false -var-file=environment/${{ inputs.env-name }}.tfvars -out=tf.plan
        continue-on-error: true
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
        
      - name: Terraform Apply
        working-directory: ${{ env.working-dir }}
        run: terraform apply -auto-approve -input=false tf.plan
